SELECT DISTINCT
    I.IMINSPECTIONID AS InspectionID,
    I.INSPECTIONNUMBER AS InspectionNumber,
    I.REQUESTEDDATE AS RequestedDate,
    I.SCHEDULEDSTARTDATE AS ScheduleDate,
    I.COMPLETE AS IsCompleted,
    INS.STATUSNAME AS InspectionStatus,
    IT.[NAME] AS InspectionType,
    CASE
        WHEN NULLIF(LTRIM(RTRIM(U.LNAME)), '') IS NULL
         AND NULLIF(LTRIM(RTRIM(U.FNAME)), '') IS NULL THEN NULL
        ELSE CONCAT(
            LTRIM(RTRIM(U.LNAME)),
            CASE WHEN NULLIF(LTRIM(RTRIM(U.FNAME)), '') IS NULL THEN '' ELSE ', ' END,
            LTRIM(RTRIM(U.FNAME))
        )
    END AS Inspector,
    LOWER(U.EMAIL) AS AssignedToEmail,
    P.PMPERMITID AS PermitID,
    P.PERMITNUMBER AS PermitNumber,
    RTRIM(
        LTRIM(MA.ADDRESSLINE1 + ' ') +
        LTRIM(MA.PREDIRECTION + ' ') +
        LTRIM(MA.ADDRESSLINE2 + ' ') +
        LTRIM(MA.STREETTYPE + ' ') +
        LTRIM(MA.POSTDIRECTION + ' ') +
        LTRIM(MA.UNITORSUITE)
    ) AS MainAddressLine1,
    RTRIM(
        CASE
            WHEN RTRIM(LTRIM(MA.CITY)) = '' THEN ''
            ELSE LTRIM(MA.CITY + ', ')
        END + LTRIM(MA.[STATE] + ' ') + MA.POSTALCODE
    ) AS MainAddressLine2,
    RTRIM(LTRIM(MA.ADDRESSLINE3)) AS MainAddressLine3,
    CAST(COALESCE(CSI.RolledInspection, 0) AS BIT) AS RolledInspectionCheckbox
FROM IMINSPECTION AS I
INNER JOIN IMINSPECTIONSTATUS AS INS
    ON I.IMINSPECTIONSTATUSID = INS.IMINSPECTIONSTATUSID
INNER JOIN IMINSPECTIONTYPE AS IT
    ON I.IMINSPECTIONTYPEID = IT.IMINSPECTIONTYPEID
LEFT JOIN DEPARTMENT AS D
    ON IT.DEPARTMENTID = D.DEPARTMENTID
INNER JOIN PMPERMIT AS P
    ON I.LINKID = P.PMPERMITID
LEFT JOIN PMPERMITADDRESS AS PMA
    ON P.PMPERMITID = PMA.PMPERMITID
    AND PMA.MAIN = 1
LEFT JOIN MAILINGADDRESS AS MA
    ON PMA.MAILINGADDRESSID = MA.MAILINGADDRESSID
LEFT JOIN IMINSPECTORREF AS IR
    ON I.IMINSPECTIONID = IR.INSPECTIONID
    AND IR.BPRIMARY = 1
LEFT JOIN USERS AS U
    ON IR.USERID = U.SUSERGUID
LEFT JOIN CUSTOMSAVERINSPECTIONS AS CSI
    ON I.IMINSPECTIONID = CSI.ID
WHERE (
        (
            I.SCHEDULEDSTARTDATE >= ?
            AND I.SCHEDULEDSTARTDATE < ?
        )
        OR (
            I.REQUESTEDDATE >= ?
            AND I.REQUESTEDDATE < ?
        )
    )
  AND LOWER(D.[NAME]) LIKE 'ds%'
  AND LOWER(D.[NAME]) NOT IN (
      'ds - engineering',
      'ds - zoning',
      'ds - right of way services'
  );
